### PR TITLE
Add config and job files for disc C/O paper

### PR DESCRIPTION
**Pull request by jymah**

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
@jymah can you add a description text for the docs? 

Alternatively you can change the docs in your fork yourself and implement the instructions for your config files there.

To do so, you just have to edit the files in the doc/source. For example Quick-Start.rst

**Comment by jymah** [comment]
@AaronDavidSchneider yes, I will do so. Umm, so I just modify Quick-Start.rst in my fork and you will be able to see the changes? Or should I submit another PR? Sorry that this is taking longer than expected.

Edit: I changed the Quick-Start.rst file in my fork and deleted the config and job files for the planet simulations (for simplicity; I did not want to explain that we need to change the gas accretion file)

**Comment by AaronDavidSchneider** [comment]
Yes that's exactly what I meant!
Nice. Let me know when you are done and I will merge it 😊

**Comment by jymah** [comment]
I am done with the changes :)

**Review by AaronDavidSchneider — APPROVED** [review]
LGTM

**Comment by AaronDavidSchneider** [comment]
Thanks @jymah!

**Pull request merged**
